# Telegram API connection settings
TELEGRAM_API_KEY = ""
WEBHOOK_CONNECTED = false
PORT = ""
WEBHOOK_URL = ""

# Database
DB_STRING = ""
DB_NAME = "hu-announcement-db-test"

# Telegram Chat ID List
FEEDBACK_CHAT_ID = 0
ADMIN_ID = 0
LOGGER_CHAT_ID = 0

DEFAULT_DEPS = ["hu-sksdb", "hu-oidb"]

# Task settings
ANNOUNCEMENT_CHECK_INTERVAL = 1800
ANNOUNCEMENT_CHECK_FIRST = 5
