TELEGRAM_API_KEY = ""
DB_STRING = ""
FEEDBACK_CHAT_ID = 0
ADMIN_ID = 0
LOGGER_CHAT_ID = 0
DEFAULT_DEPS = ["hu-sksdb", "hu-oidb"]
ANNOUNCEMENT_CHECK_INTERVAL = 1800
ANNOUNCEMENT_CHECK_FIRST = 5
WEBHOOK_CONNECTED = false
PORT = ""
WEBHOOK_URL = ""
